module.exports = {
  enter: "Authorization",
  password: "password",
  login: "Login",
  registration: "Registration",
  login_error_description: "Login or password not registered",
  success_registration_message: "You have successfully registered!",
  error_registration_message: "An error occurred while registering the user.",
  signUp:"Sign Up",
  error_password_signUp_message: "The minimum password length is 6 characters. The password language is English. The password must contain at least one uppercase letter and at least one number.",
  error_email_signUp_message:"This email or this login is already registered.",
  error_email_proof_signUp_message:"The password and its confirmation must match.",
  confirmThePassword: "confirm the password",
  yourLogin: "login",
  success_trackDelete_message: 'The removal was successful.',
  error_trackDelete_message: 'An error occurred during deletion.',
  button_returnToTrackList:'Back to the list of tracks.',
  run: 'Run',
  bike: 'Bike',
  hike: 'Hike',
  ski: 'Ski',
  kayak: 'Kayak',
  other: 'Other',
  all: "All",
  allTracks: "All tracks",
  typeOfSport: "Type of sport",
  date: "Data",
  title: "Title",
  distance: "Distance, km",
  download: "download",
  delete: "delete",
  success_trackLoad_message:"You have successfully uploaded a track!",
  error_trackLoad_message:"An error occurred during the download.",
  button_newTrack: "Upload a new track",
  button_editTrack: "Edit track",
  selectFile: "Select file",
  send: "Send",
  privateTrack: "Private track",
  trackTitle: "Track title",
  trackDescription:"Track description",
  uploadTrack: "Upload track",
  trackList:"Track list",
  myTrackList:"List of my tracks",
  logout: "Log out",
  ru: "rus.",
  en: "eng.",
  createVariation: 'create a variation',
  addToBookmarks: 'add to bookmarks',
  edit: "edit",
  statistics: "statistics",
  author:"author",
  uploaded: "uploaded",
  fullStatistics: "Full statistics",
  km: "km",
  noTracks:"No tracks yet",
  points:"Points:",
  button_viewTrack: "View track",
  button_backTrackPreview:"Back to the track preview",
  myPage: "My page",
  favorites: "Favorites",
  friends: "Friends",
  settings: "Settings",
  language: "Language",
  visibleToAll: "visible to all",
  private: "private",
};
